spring.application.name=activity-13-cinema-seat-manager

spring.datasource.url=jdbc:mysql://localhost:3306/cinema_seat_manager
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true

# With this, Hibernate creates the @Entity as a table in the DB
spring.jpa.hibernate.ddl-auto=update