### GET all books
GET http://localhost:8080/books

### GET book by id
GET http://localhost:8080/books/1

### GET book by id (unexistant)
GET http://localhost:8080/books/999

### POST loan by id
POST http://localhost:8080/loans
Content-Type: application/json

{
  "bookId": 1
}

### POST loan by id (unexistant)
POST http://localhost:8080/loans
Content-Type: application/json

{
  "bookId": 999
}

### POST loan by id (unavailable)
POST http://localhost:8080/loans
Content-Type: application/json

{
  "bookId": 2
}


